In [1]:
# "#" Ovo je znak za komentar.
# Uvezilo smo biblioteku numpy kao instancu np koristeci komandu import

import numpy as np

In [2]:
# np sada mozemo koristiti u velikom broju primera.
# ukoliko otkucamo np i pritisnemo TAB dobicemo listu mogucih funkcija

#kreiramo niz od 6 elemenata
a = np.array([0,1,2,3,4,5
             ])

In [3]:
# a * 3 u slucaju da je numpy instanca, mnozi svaki element sa 3
a = a * 3

In [4]:
print(a)

[ 0  3  6  9 12 15]


In [5]:
# ovim smo generisali niz od 6 elemenata.
# mozemo proveriti dimenzije niza. U ovom slucaju rezultat 1 nam
# govori da se radi o vektoru
a.ndim

1

In [6]:
#komandom reshape mozemo promeniti oblik niza. Od 1D niza(1x6), mozemo kreirati matricu, 2D niz, dimenzija (2x3)
a.reshape(2,3)

array([[ 0,  3,  6],
       [ 9, 12, 15]])

In [7]:
b = np.zeros((3,4))

In [8]:
b

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [10]:
x = np.array([[1.,2.,3.],[4.,5.,6.]])

In [11]:
print(x)

[[ 1.  2.  3.]
 [ 4.  5.  6.]]


In [12]:
x * 3

array([[  3.,   6.,   9.],
       [ 12.,  15.,  18.]])

# Indeksiranje

In [14]:
N = 10
x = np.arange(N)

In [15]:
# ovom naredbom type mozemo proveriti koji je tip podatka x. --> numpy.ndarray
type(x)

numpy.ndarray

In [16]:
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
# indeksiranje pocinje od 0, do N-1
x[0]

0

In [20]:
print(x[1], x[2], x[3])

1 2 3


In [21]:
print (x[2:5])

[2 3 4]


# Element processing